# Enable AndroidX and auto-convert third-party libraries to use AndroidX
android.useAndroidX=true
android.enableJetifier=true

# JVM parameters for the Gradle Daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use Kotlin parallel compilation
kotlin.incremental=true
kotlin.code.style=official
